#Some minimal settings (You don't have to edit them)

#Give kits to new players? (true,false)
give: true

#What the starter kit is saved under in kits.yml
starter-kit-name: "starter-kit"

#Message if the player already has items in the inventory slot
conflict-message: "§cYou received a starter kit, but you already had items in your inventory! The conflicting items were dropped."#red

#Are new players ones not seen before by the server or the plugin? (server,plugin)
#For example, a player who played on the server before the plugin was installed would not have been seen before by the plugin
#Players who the plugin has seen before are stored in played_before.yml
new: "plugin"