name: SimpleStarterKits
version: ${project.version}
main: me.noob.simplestarterkits.SimpleStarterKits
api-version: 1.19
description: An easy to use starter kit plugin.
#add website here
commands:
  SimpleStarterKits:
    description: The main (and only) command for the SimpleStarterKits plugin. Use /simplestarterkits help for more information
    aliases: ssk
    permission: simplestarterkits.command
    permission-message: "§cYou do not have permission to use this command."#red
    usage: "§c§lInvalid command!\n§r§cUsage: /<command> [help|reload|set|give|about|clear]\nUse /<command> help for more information"
permissions:
  simplestarterkits.command:
    description: allows usage of command