name: SimpleStarterKits
version: ${project.version}
main: me.noob.simplestarterkits.SimpleStarterKits
api-version: 1.19
description: An easy to use starter kit plugin.
#add website here
commands:
  SimpleStarterKits:
    description: The main (and only) command for the SimpleStarterKits plugin. Use /simplestarterkits help for more information
    aliases: ssk
    usage: "Usage: /<command> [help|reload|save|give|about]"
permissions:
  simplestarterkits.save:
    description: can set kits
  simplestarterkits.give:
    description: can give kits
  simplestarterkits.reload:
    description: can reload the plugin